/**
 * Service scaffolder
 * Generates directory structure and starter code for containers and functions
 */

import type {
  StackSoloConfig,
  ContainerConfig,
  FunctionConfig,
} from '@stacksolo/blueprint';
import type { ServiceScaffold, GeneratedFile } from './types.js';

interface ServicesGeneratorResult {
  services: ServiceScaffold[];
  files: GeneratedFile[];
}

/**
 * Generate service scaffolds from config
 */
export function generateServiceScaffolds(config: StackSoloConfig): ServicesGeneratorResult {
  const services: ServiceScaffold[] = [];
  const allFiles: GeneratedFile[] = [];

  for (const network of config.project.networks || []) {
    // Generate container scaffolds
    for (const container of network.containers || []) {
      const scaffold = generateContainerScaffold(container, config);
      services.push(scaffold);
      allFiles.push(...scaffold.files);
    }

    // Generate function scaffolds
    for (const func of network.functions || []) {
      const scaffold = generateFunctionScaffold(func, config);
      services.push(scaffold);
      allFiles.push(...scaffold.files);
    }
  }

  return { services, files: allFiles };
}

function generateContainerScaffold(container: ContainerConfig, config: StackSoloConfig): ServiceScaffold {
  const servicePath = `services/${container.name}`;
  const files: GeneratedFile[] = [];

  // Dockerfile
  files.push({
    path: `${servicePath}/Dockerfile`,
    content: generateContainerDockerfile(container),
  });

  // package.json
  files.push({
    path: `${servicePath}/package.json`,
    content: generateContainerPackageJson(container, config),
  });

  // tsconfig.json
  files.push({
    path: `${servicePath}/tsconfig.json`,
    content: generateTsConfig(),
  });

  // src/index.ts
  files.push({
    path: `${servicePath}/src/index.ts`,
    content: generateContainerEntrypoint(container),
  });

  // .gitignore
  files.push({
    path: `${servicePath}/.gitignore`,
    content: generateGitignore(),
  });

  return {
    name: container.name,
    type: 'container',
    files,
  };
}

function generateFunctionScaffold(func: FunctionConfig, config: StackSoloConfig): ServiceScaffold {
  const servicePath = `services/${func.name}`;
  const files: GeneratedFile[] = [];

  // package.json
  files.push({
    path: `${servicePath}/package.json`,
    content: generateFunctionPackageJson(func, config),
  });

  // tsconfig.json
  files.push({
    path: `${servicePath}/tsconfig.json`,
    content: generateTsConfig(),
  });

  // src/index.ts
  files.push({
    path: `${servicePath}/src/index.ts`,
    content: generateFunctionEntrypoint(func),
  });

  // .gitignore
  files.push({
    path: `${servicePath}/.gitignore`,
    content: generateGitignore(),
  });

  return {
    name: func.name,
    type: 'function',
    files,
  };
}

function generateContainerDockerfile(container: ContainerConfig): string {
  const port = container.port || 8080;
  return `# ${container.name} container
# Generated by: stacksolo scaffold

FROM node:20-slim AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# Build
RUN npm run build

# Production image
FROM node:20-slim

WORKDIR /app

# Copy built files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "dist/index.js"]
`;
}

function generateContainerPackageJson(container: ContainerConfig, config: StackSoloConfig): string {
  const pkg = {
    name: `@${config.project.name}/${container.name}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'tsx watch src/index.ts',
      build: 'tsc',
      start: 'node dist/index.js',
      lint: 'eslint src/',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      express: '^4.18.2',
    },
    devDependencies: {
      '@types/express': '^4.17.21',
      '@types/node': '^20.10.0',
      tsx: '^4.6.0',
      typescript: '^5.3.0',
    },
  };

  return JSON.stringify(pkg, null, 2) + '\n';
}

function generateFunctionPackageJson(func: FunctionConfig, config: StackSoloConfig): string {
  const pkg = {
    name: `@${config.project.name}/${func.name}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    main: 'dist/index.js',
    scripts: {
      dev: 'functions-framework --source=src --target=handler',
      build: 'tsc',
      start: 'functions-framework --source=dist --target=handler',
      lint: 'eslint src/',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      '@google-cloud/functions-framework': '^3.3.0',
    },
    devDependencies: {
      '@types/node': '^20.10.0',
      tsx: '^4.6.0',
      typescript: '^5.3.0',
    },
  };

  return JSON.stringify(pkg, null, 2) + '\n';
}

function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      esModuleInterop: true,
      strict: true,
      skipLibCheck: true,
      outDir: 'dist',
      rootDir: 'src',
      declaration: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };

  return JSON.stringify(config, null, 2) + '\n';
}

function generateContainerEntrypoint(container: ContainerConfig): string {
  const port = container.port || 8080;

  // Build env imports based on referenced secrets/resources
  const envVars = Object.keys(container.env || {});
  const envImports = envVars.length > 0
    ? `// Environment variables from config:\n${envVars.map(k => `// - ${k}`).join('\n')}\n`
    : '';

  return `/**
 * ${container.name} service entrypoint
 * Generated by: stacksolo scaffold
 */

import express from 'express';

${envImports}
const app = express();
const port = process.env.PORT || ${port};

app.use(express.json());

// Health check endpoint
app.get('/health', (_req, res) => {
  res.json({ status: 'healthy' });
});

// Main endpoint
app.get('/', (_req, res) => {
  res.json({
    service: '${container.name}',
    message: 'Hello from ${container.name}!'
  });
});

app.listen(port, () => {
  console.log(\`${container.name} listening on port \${port}\`);
});
`;
}

function generateFunctionEntrypoint(func: FunctionConfig): string {
  const trigger = func.trigger || { type: 'http' };

  if (trigger.type === 'http') {
    return generateHttpFunctionEntrypoint(func);
  } else if (trigger.type === 'pubsub') {
    return generatePubSubFunctionEntrypoint(func, trigger.topic || 'unknown');
  } else if (trigger.type === 'storage') {
    return generateStorageFunctionEntrypoint(func, trigger.bucket || 'unknown');
  }

  return generateHttpFunctionEntrypoint(func);
}

function generateHttpFunctionEntrypoint(func: FunctionConfig): string {
  return `/**
 * ${func.name} HTTP function
 * Generated by: stacksolo scaffold
 */

import type { Request, Response } from '@google-cloud/functions-framework';

export function handler(req: Request, res: Response): void {
  console.log('${func.name} invoked', { method: req.method, path: req.path });

  res.json({
    function: '${func.name}',
    message: 'Hello from ${func.name}!',
  });
}
`;
}

function generatePubSubFunctionEntrypoint(func: FunctionConfig, topic: string): string {
  return `/**
 * ${func.name} Pub/Sub function
 * Triggered by: ${topic}
 * Generated by: stacksolo scaffold
 */

import type { CloudEvent } from '@google-cloud/functions-framework';

interface PubSubMessage {
  message: {
    data: string;
    attributes?: Record<string, string>;
    messageId: string;
    publishTime: string;
  };
  subscription: string;
}

export function handler(event: CloudEvent<PubSubMessage>): void {
  const message = event.data?.message;

  if (!message) {
    console.error('No message received');
    return;
  }

  // Decode the message data
  const data = message.data
    ? JSON.parse(Buffer.from(message.data, 'base64').toString())
    : {};

  console.log('${func.name} received message', {
    messageId: message.messageId,
    data,
    attributes: message.attributes,
  });

  // TODO: Process the message
}
`;
}

function generateStorageFunctionEntrypoint(func: FunctionConfig, bucket: string): string {
  return `/**
 * ${func.name} Storage function
 * Triggered by: ${bucket} bucket events
 * Generated by: stacksolo scaffold
 */

import type { CloudEvent } from '@google-cloud/functions-framework';

interface StorageObjectData {
  bucket: string;
  name: string;
  metageneration: string;
  timeCreated: string;
  updated: string;
}

export function handler(event: CloudEvent<StorageObjectData>): void {
  const data = event.data;

  if (!data) {
    console.error('No data received');
    return;
  }

  console.log('${func.name} triggered', {
    bucket: data.bucket,
    file: data.name,
    event: event.type,
  });

  // TODO: Process the storage event
}
`;
}

function generateGitignore(): string {
  return `# Dependencies
node_modules/

# Build output
dist/

# Logs
*.log

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
`;
}
