import { registry } from '@stacksolo/core';
import type { Resource, Project, GeneratedFile } from '@stacksolo/shared';

export class CodegenService {
  /**
   * Generate Pulumi code for a project and its resources
   */
  generateProjectCode(project: Project, resources: Resource[]): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Collect all code from resources
    const allImports = new Set<string>();
    const allCode: string[] = [];
    const allOutputs: string[] = [];

    for (const resource of resources) {
      const resourceType = registry.getResource(resource.type);
      if (!resourceType) {
        console.warn(`Unknown resource type: ${resource.type}`);
        continue;
      }

      const generated = resourceType.generate({
        name: resource.name,
        ...resource.config,
      });

      generated.imports.forEach((imp) => allImports.add(imp));
      allCode.push(`// ${resource.name} (${resourceType.name})`);
      allCode.push(generated.code);
      allCode.push('');

      if (generated.outputs) {
        allOutputs.push(...generated.outputs);
      }
    }

    // Generate index.ts
    const indexContent = this.generateIndexTs(
      project,
      Array.from(allImports),
      allCode,
      allOutputs
    );
    files.push({ path: 'index.ts', content: indexContent });

    // Generate Pulumi.yaml
    const pulumiYaml = this.generatePulumiYaml(project);
    files.push({ path: 'Pulumi.yaml', content: pulumiYaml });

    // Generate package.json
    const packageJson = this.generatePackageJson(project);
    files.push({ path: 'package.json', content: packageJson });

    // Generate tsconfig.json
    const tsconfig = this.generateTsconfig();
    files.push({ path: 'tsconfig.json', content: tsconfig });

    return files;
  }

  private generateIndexTs(
    project: Project,
    imports: string[],
    code: string[],
    outputs: string[]
  ): string {
    const lines: string[] = [];

    // Imports - always add pulumi first, then filter duplicates from resource imports
    lines.push("import * as pulumi from '@pulumi/pulumi';");
    imports
      .filter((imp) => !imp.includes('@pulumi/pulumi'))
      .forEach((imp) => lines.push(imp));
    lines.push('');

    // Config
    lines.push('// Configuration');
    lines.push('const config = new pulumi.Config();');
    if (project.provider === 'gcp' && project.providerConfig.projectId) {
      lines.push(`const gcpProject = config.get("gcp:project") || "${project.providerConfig.projectId}";`);
    }
    if (project.providerConfig.region) {
      lines.push(`const region = config.get("region") || "${project.providerConfig.region}";`);
    }
    lines.push('');

    // Resources
    lines.push('// Resources');
    lines.push(...code);

    // Outputs
    if (outputs.length > 0) {
      lines.push('// Outputs');
      lines.push(...outputs);
    }

    return lines.join('\n');
  }

  private generatePulumiYaml(project: Project): string {
    const projectName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    return `name: ${projectName}
runtime: nodejs
description: Infrastructure for ${project.name} - generated by StackSolo
`;
  }

  private generatePackageJson(project: Project): string {
    const projectName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const deps: Record<string, string> = {
      '@pulumi/pulumi': '^3.0.0',
    };

    if (project.provider === 'gcp') {
      deps['@pulumi/gcp'] = '^7.0.0';
    }

    return JSON.stringify(
      {
        name: projectName,
        main: 'index.ts',
        devDependencies: {
          typescript: '^5.0.0',
          '@types/node': '^18.0.0',
        },
        dependencies: deps,
      },
      null,
      2
    );
  }

  private generateTsconfig(): string {
    return JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          module: 'commonjs',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          outDir: 'bin',
        },
        include: ['*.ts'],
      },
      null,
      2
    );
  }
}
