/**
 * Chart.yaml Generator
 */

export interface ChartYamlOptions {
  name: string;
  version: string;
  appVersion: string;
  description?: string;
}

export function generateChartYaml(options: ChartYamlOptions): string {
  const description = options.description || `A Helm chart for ${options.name} generated by StackSolo`;

  return `apiVersion: v2
name: ${options.name}
description: ${description}
type: application
version: ${options.version}
appVersion: "${options.appVersion}"
maintainers:
  - name: StackSolo
    url: https://stacksolo.dev
`;
}
