/**
 * Container scaffolder
 * Generates directory structure and starter code for Cloud Run containers
 */

import type { StackSoloConfig, ContainerConfig } from '@stacksolo/blueprint';
import type { ServiceScaffold, GeneratedFile } from '../types';

export function generateContainerScaffold(
  container: ContainerConfig,
  config: StackSoloConfig
): ServiceScaffold {
  // Use sourceDir from config if provided, otherwise default to containers/<name>
  const servicePath =
    (container as { sourceDir?: string }).sourceDir?.replace(/^\.\//, '') ||
    `containers/${container.name}`;
  const files: GeneratedFile[] = [];

  // Dockerfile
  files.push({
    path: `${servicePath}/Dockerfile`,
    content: generateContainerDockerfile(container),
  });

  // package.json
  files.push({
    path: `${servicePath}/package.json`,
    content: generateContainerPackageJson(container, config),
  });

  // tsconfig.json
  files.push({
    path: `${servicePath}/tsconfig.json`,
    content: generateTsConfig(),
  });

  // src/index.ts
  files.push({
    path: `${servicePath}/src/index.ts`,
    content: generateContainerEntrypoint(container),
  });

  // .gitignore
  files.push({
    path: `${servicePath}/.gitignore`,
    content: generateGitignore(),
  });

  return {
    name: container.name,
    type: 'container',
    files,
  };
}

function generateContainerDockerfile(container: ContainerConfig): string {
  const port = container.port || 8080;
  return `# ${container.name} container
# Generated by: stacksolo scaffold

FROM node:20-slim AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# Build
RUN npm run build

# Production image
FROM node:20-slim

WORKDIR /app

# Copy built files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "dist/index.js"]
`;
}

function generateContainerPackageJson(
  container: ContainerConfig,
  config: StackSoloConfig
): string {
  const pkg = {
    name: `@${config.project.name}/${container.name}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'tsx watch src/index.ts',
      build: 'tsc',
      start: 'node dist/index.js',
      lint: 'eslint src/',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      express: '^4.18.2',
      '@stacksolo/runtime': '^0.1.0',
    },
    devDependencies: {
      '@types/express': '^4.17.21',
      '@types/node': '^20.10.0',
      tsx: '^4.6.0',
      typescript: '^5.3.0',
    },
  };

  return JSON.stringify(pkg, null, 2) + '\n';
}

function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      esModuleInterop: true,
      strict: true,
      skipLibCheck: true,
      outDir: 'dist',
      rootDir: 'src',
      declaration: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };

  return JSON.stringify(config, null, 2) + '\n';
}

function generateContainerEntrypoint(container: ContainerConfig): string {
  const port = container.port || 8080;

  // Build env imports based on referenced secrets/resources
  const envVars = Object.keys(container.env || {});
  const envImports =
    envVars.length > 0
      ? `// Environment variables from config:\n${envVars.map((k) => `// - ${k}`).join('\n')}\n`
      : '';

  return `/**
 * ${container.name} service entrypoint
 * Generated by: stacksolo scaffold
 */

import express from 'express';

${envImports}
const app = express();
const port = process.env.PORT || ${port};

app.use(express.json());

// Health check endpoint
app.get('/health', (_req, res) => {
  res.json({ status: 'healthy' });
});

// Main endpoint
app.get('/', (_req, res) => {
  res.json({
    service: '${container.name}',
    message: 'Hello from ${container.name}!'
  });
});

app.listen(port, () => {
  console.log(\`${container.name} listening on port \${port}\`);
});
`;
}

function generateGitignore(): string {
  return `# Dependencies
node_modules/

# Build output
dist/

# Logs
*.log

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
`;
}
