/**
 * Function scaffolder
 * Generates directory structure and starter code for Cloud Functions
 */

import type { StackSoloConfig, FunctionConfig } from '@stacksolo/blueprint';
import type { ServiceScaffold, GeneratedFile } from '../types';

export function generateFunctionScaffold(
  func: FunctionConfig,
  config: StackSoloConfig
): ServiceScaffold {
  // Use sourceDir from config if provided, otherwise default to functions/<name>
  const servicePath =
    func.sourceDir?.replace(/^\.\//, '') || `functions/${func.name}`;
  const files: GeneratedFile[] = [];

  // package.json
  files.push({
    path: `${servicePath}/package.json`,
    content: generateFunctionPackageJson(func, config),
  });

  // tsconfig.json
  files.push({
    path: `${servicePath}/tsconfig.json`,
    content: generateTsConfig(),
  });

  // src/index.ts
  files.push({
    path: `${servicePath}/src/index.ts`,
    content: generateFunctionEntrypoint(func),
  });

  // .gitignore
  files.push({
    path: `${servicePath}/.gitignore`,
    content: generateGitignore(),
  });

  return {
    name: func.name,
    type: 'function',
    files,
  };
}

function generateFunctionPackageJson(
  func: FunctionConfig,
  config: StackSoloConfig
): string {
  const pkg = {
    name: `@${config.project.name}/${func.name}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    main: 'dist/index.js',
    scripts: {
      dev: 'functions-framework --source=src --target=handler',
      build: 'tsc',
      start: 'functions-framework --source=dist --target=handler',
      lint: 'eslint src/',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      '@google-cloud/functions-framework': '^3.3.0',
    },
    devDependencies: {
      '@types/node': '^20.10.0',
      tsx: '^4.6.0',
      typescript: '^5.3.0',
    },
  };

  return JSON.stringify(pkg, null, 2) + '\n';
}

function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      esModuleInterop: true,
      strict: true,
      skipLibCheck: true,
      outDir: 'dist',
      rootDir: 'src',
      declaration: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };

  return JSON.stringify(config, null, 2) + '\n';
}

function generateFunctionEntrypoint(func: FunctionConfig): string {
  const trigger = func.trigger || { type: 'http' };

  if (trigger.type === 'http') {
    return generateHttpFunctionEntrypoint(func);
  } else if (trigger.type === 'pubsub') {
    return generatePubSubFunctionEntrypoint(func, trigger.topic || 'unknown');
  } else if (trigger.type === 'storage') {
    return generateStorageFunctionEntrypoint(func, trigger.bucket || 'unknown');
  }

  return generateHttpFunctionEntrypoint(func);
}

function generateHttpFunctionEntrypoint(func: FunctionConfig): string {
  return `/**
 * ${func.name} HTTP function
 * Generated by: stacksolo scaffold
 */

import type { Request, Response } from '@google-cloud/functions-framework';

export function handler(req: Request, res: Response): void {
  console.log('${func.name} invoked', { method: req.method, path: req.path });

  res.json({
    function: '${func.name}',
    message: 'Hello from ${func.name}!',
  });
}
`;
}

function generatePubSubFunctionEntrypoint(
  func: FunctionConfig,
  topic: string
): string {
  return `/**
 * ${func.name} Pub/Sub function
 * Triggered by: ${topic}
 * Generated by: stacksolo scaffold
 */

import type { CloudEvent } from '@google-cloud/functions-framework';

interface PubSubMessage {
  message: {
    data: string;
    attributes?: Record<string, string>;
    messageId: string;
    publishTime: string;
  };
  subscription: string;
}

export function handler(event: CloudEvent<PubSubMessage>): void {
  const message = event.data?.message;

  if (!message) {
    console.error('No message received');
    return;
  }

  // Decode the message data
  const data = message.data
    ? JSON.parse(Buffer.from(message.data, 'base64').toString())
    : {};

  console.log('${func.name} received message', {
    messageId: message.messageId,
    data,
    attributes: message.attributes,
  });

  // TODO: Process the message
}
`;
}

function generateStorageFunctionEntrypoint(
  func: FunctionConfig,
  bucket: string
): string {
  return `/**
 * ${func.name} Storage function
 * Triggered by: ${bucket} bucket events
 * Generated by: stacksolo scaffold
 */

import type { CloudEvent } from '@google-cloud/functions-framework';

interface StorageObjectData {
  bucket: string;
  name: string;
  metageneration: string;
  timeCreated: string;
  updated: string;
}

export function handler(event: CloudEvent<StorageObjectData>): void {
  const data = event.data;

  if (!data) {
    console.error('No data received');
    return;
  }

  console.log('${func.name} triggered', {
    bucket: data.bucket,
    file: data.name,
    event: event.type,
  });

  // TODO: Process the storage event
}
`;
}

function generateGitignore(): string {
  return `# Dependencies
node_modules/

# Build output
dist/

# Logs
*.log

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
`;
}
