/**
 * UI scaffolder
 * Generates directory structure and starter code for static UI sites
 * Supports React, Vue, SvelteKit, and plain HTML
 */

import type { StackSoloConfig, UIConfig } from '@stacksolo/blueprint';
import type { ServiceScaffold, GeneratedFile } from '../types';

export function generateUIScaffold(
  ui: UIConfig,
  config: StackSoloConfig
): ServiceScaffold {
  // Use sourceDir from config if provided, otherwise default to ui/<name>
  // This matches the K8s generator default path
  const uiPath = ui.sourceDir?.replace(/^\.\//, '') || `ui/${ui.name}`;
  const framework = ui.framework || 'react';

  switch (framework) {
    case 'react':
      return generateReactUIScaffold(ui, config, uiPath);
    case 'vue':
      return generateVueUIScaffold(ui, config, uiPath);
    case 'sveltekit':
      return generateSvelteKitUIScaffold(ui, config, uiPath);
    case 'html':
      return generateHTMLUIScaffold(ui, config, uiPath);
    default:
      return generateReactUIScaffold(ui, config, uiPath);
  }
}

function generateReactUIScaffold(
  ui: UIConfig,
  config: StackSoloConfig,
  uiPath: string
): ServiceScaffold {
  const files: GeneratedFile[] = [];

  // package.json
  files.push({
    path: `${uiPath}/package.json`,
    content:
      JSON.stringify(
        {
          name: `@${config.project.name}/${ui.name}`,
          version: '0.1.0',
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc && vite build',
            preview: 'vite preview',
            lint: 'eslint src/',
            typecheck: 'tsc --noEmit',
          },
          dependencies: {
            react: '^18.2.0',
            'react-dom': '^18.2.0',
          },
          devDependencies: {
            '@types/react': '^18.2.0',
            '@types/react-dom': '^18.2.0',
            '@vitejs/plugin-react': '^4.2.0',
            typescript: '^5.3.0',
            vite: '^5.0.0',
          },
        },
        null,
        2
      ) + '\n',
  });

  // tsconfig.json
  files.push({
    path: `${uiPath}/tsconfig.json`,
    content:
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowImportingTsExtensions: true,
            resolveJsonModule: true,
            isolatedModules: true,
            noEmit: true,
            jsx: 'react-jsx',
            strict: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            noFallthroughCasesInSwitch: true,
          },
          include: ['src'],
          references: [{ path: './tsconfig.node.json' }],
        },
        null,
        2
      ) + '\n',
  });

  // tsconfig.node.json
  files.push({
    path: `${uiPath}/tsconfig.node.json`,
    content:
      JSON.stringify(
        {
          compilerOptions: {
            composite: true,
            skipLibCheck: true,
            module: 'ESNext',
            moduleResolution: 'bundler',
            allowSyntheticDefaultImports: true,
          },
          include: ['vite.config.ts'],
        },
        null,
        2
      ) + '\n',
  });

  // vite.config.ts
  files.push({
    path: `${uiPath}/vite.config.ts`,
    content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
  },
});
`,
  });

  // index.html
  files.push({
    path: `${uiPath}/index.html`,
    content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${ui.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
  });

  // src/main.tsx
  files.push({
    path: `${uiPath}/src/main.tsx`,
    content: `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`,
  });

  // src/App.tsx
  files.push({
    path: `${uiPath}/src/App.tsx`,
    content: `/**
 * ${ui.name} React App
 * Generated by: stacksolo scaffold
 */

import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <h1>${ui.name}</h1>
      <p>Welcome to your React app!</p>
      <button onClick={() => setCount((c) => c + 1)}>
        Count: {count}
      </button>
    </div>
  );
}

export default App;
`,
  });

  // src/index.css
  files.push({
    path: `${uiPath}/src/index.css`,
    content: `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color: #213547;
  background-color: #ffffff;
}

.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #f9f9f9;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #646cff;
}
`,
  });

  // .gitignore
  files.push({
    path: `${uiPath}/.gitignore`,
    content: generateUIGitignore(),
  });

  return {
    name: ui.name,
    type: 'ui',
    files,
  };
}

function generateVueUIScaffold(
  ui: UIConfig,
  config: StackSoloConfig,
  uiPath: string
): ServiceScaffold {
  const files: GeneratedFile[] = [];

  // package.json
  files.push({
    path: `${uiPath}/package.json`,
    content:
      JSON.stringify(
        {
          name: `@${config.project.name}/${ui.name}`,
          version: '0.1.0',
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vue-tsc -b && vite build',
            preview: 'vite preview',
            lint: 'eslint src/',
            typecheck: 'vue-tsc --noEmit',
          },
          dependencies: {
            vue: '^3.4.0',
          },
          devDependencies: {
            '@vitejs/plugin-vue': '^5.0.0',
            typescript: '~5.6.0',
            vite: '^5.0.0',
            'vue-tsc': '^2.0.0',
          },
        },
        null,
        2
      ) + '\n',
  });

  // tsconfig.json
  files.push({
    path: `${uiPath}/tsconfig.json`,
    content:
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            module: 'ESNext',
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowImportingTsExtensions: true,
            resolveJsonModule: true,
            isolatedModules: true,
            noEmit: true,
            jsx: 'preserve',
            strict: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            noFallthroughCasesInSwitch: true,
          },
          include: ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.vue'],
          references: [{ path: './tsconfig.node.json' }],
        },
        null,
        2
      ) + '\n',
  });

  // tsconfig.node.json
  files.push({
    path: `${uiPath}/tsconfig.node.json`,
    content:
      JSON.stringify(
        {
          compilerOptions: {
            composite: true,
            skipLibCheck: true,
            module: 'ESNext',
            moduleResolution: 'bundler',
            allowSyntheticDefaultImports: true,
          },
          include: ['vite.config.ts'],
        },
        null,
        2
      ) + '\n',
  });

  // vite.config.ts
  files.push({
    path: `${uiPath}/vite.config.ts`,
    content: `import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
  plugins: [vue()],
  server: {
    port: 3000,
  },
});
`,
  });

  // index.html
  files.push({
    path: `${uiPath}/index.html`,
    content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${ui.name}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`,
  });

  // src/main.ts
  files.push({
    path: `${uiPath}/src/main.ts`,
    content: `import { createApp } from 'vue';
import App from './App.vue';
import './style.css';

createApp(App).mount('#app');
`,
  });

  // src/App.vue
  files.push({
    path: `${uiPath}/src/App.vue`,
    content: `<!--
  ${ui.name} Vue App
  Generated by: stacksolo scaffold
-->

<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div class="app">
    <h1>${ui.name}</h1>
    <p>Welcome to your Vue app!</p>
    <button @click="count++">
      Count: {{ count }}
    </button>
  </div>
</template>

<style scoped>
.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #f9f9f9;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #42b883;
}
</style>
`,
  });

  // src/style.css
  files.push({
    path: `${uiPath}/src/style.css`,
    content: `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color: #213547;
  background-color: #ffffff;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

#app {
  width: 100%;
}
`,
  });

  // src/vite-env.d.ts
  files.push({
    path: `${uiPath}/src/vite-env.d.ts`,
    content: `/// <reference types="vite/client" />
`,
  });

  // .gitignore
  files.push({
    path: `${uiPath}/.gitignore`,
    content: generateUIGitignore(),
  });

  return {
    name: ui.name,
    type: 'ui',
    files,
  };
}

function generateSvelteKitUIScaffold(
  ui: UIConfig,
  config: StackSoloConfig,
  uiPath: string
): ServiceScaffold {
  const files: GeneratedFile[] = [];

  // package.json
  files.push({
    path: `${uiPath}/package.json`,
    content:
      JSON.stringify(
        {
          name: `@${config.project.name}/${ui.name}`,
          version: '0.1.0',
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite dev',
            build: 'vite build',
            preview: 'vite preview',
            check: 'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json',
          },
          devDependencies: {
            '@sveltejs/adapter-static': '^3.0.0',
            '@sveltejs/kit': '^2.0.0',
            '@sveltejs/vite-plugin-svelte': '^3.0.0',
            svelte: '^4.2.0',
            'svelte-check': '^3.6.0',
            typescript: '^5.3.0',
            vite: '^5.0.0',
          },
        },
        null,
        2
      ) + '\n',
  });

  // svelte.config.js
  files.push({
    path: `${uiPath}/svelte.config.js`,
    content: `import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      pages: 'build',
      assets: 'build',
      fallback: 'index.html',
      precompress: false,
      strict: true,
    }),
  },
};

export default config;
`,
  });

  // vite.config.ts
  files.push({
    path: `${uiPath}/vite.config.ts`,
    content: `import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  server: {
    port: 3000,
  },
});
`,
  });

  // tsconfig.json
  files.push({
    path: `${uiPath}/tsconfig.json`,
    content:
      JSON.stringify(
        {
          extends: './.svelte-kit/tsconfig.json',
          compilerOptions: {
            allowJs: true,
            checkJs: true,
            esModuleInterop: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true,
            skipLibCheck: true,
            sourceMap: true,
            strict: true,
            moduleResolution: 'bundler',
          },
        },
        null,
        2
      ) + '\n',
  });

  // src/app.html
  files.push({
    path: `${uiPath}/src/app.html`,
    content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%sveltekit.assets%/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
`,
  });

  // src/app.css
  files.push({
    path: `${uiPath}/src/app.css`,
    content: `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color: #213547;
  background-color: #ffffff;
}

.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #f9f9f9;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #ff3e00;
}
`,
  });

  // src/routes/+layout.svelte
  files.push({
    path: `${uiPath}/src/routes/+layout.svelte`,
    content: `<script>
  import '../app.css';
</script>

<slot />
`,
  });

  // src/routes/+layout.ts (for static adapter)
  files.push({
    path: `${uiPath}/src/routes/+layout.ts`,
    content: `export const prerender = true;
export const ssr = false;
`,
  });

  // src/routes/+page.svelte
  files.push({
    path: `${uiPath}/src/routes/+page.svelte`,
    content: `<!--
  ${ui.name} SvelteKit App
  Generated by: stacksolo scaffold
-->

<script lang="ts">
  let count = 0;
</script>

<svelte:head>
  <title>${ui.name}</title>
</svelte:head>

<div class="app">
  <h1>${ui.name}</h1>
  <p>Welcome to your SvelteKit app!</p>
  <button on:click={() => count++}>
    Count: {count}
  </button>
</div>
`,
  });

  // static/favicon.png placeholder
  files.push({
    path: `${uiPath}/static/.gitkeep`,
    content: '',
  });

  // .gitignore
  files.push({
    path: `${uiPath}/.gitignore`,
    content: generateUIGitignore() + '.svelte-kit/\n',
  });

  return {
    name: ui.name,
    type: 'ui',
    files,
  };
}

function generateHTMLUIScaffold(
  ui: UIConfig,
  config: StackSoloConfig,
  uiPath: string
): ServiceScaffold {
  const files: GeneratedFile[] = [];

  // index.html
  files.push({
    path: `${uiPath}/index.html`,
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ui.name}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="app">
    <h1>${ui.name}</h1>
    <p>Welcome to your static site!</p>
    <button id="counter">Count: 0</button>
  </div>
  <script src="script.js"></script>
</body>
</html>
`,
  });

  // styles.css
  files.push({
    path: `${uiPath}/styles.css`,
    content: `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color: #213547;
  background-color: #ffffff;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
  width: 100%;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #f9f9f9;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #646cff;
}
`,
  });

  // script.js
  files.push({
    path: `${uiPath}/script.js`,
    content: `/**
 * ${ui.name} JavaScript
 * Generated by: stacksolo scaffold
 */

document.addEventListener('DOMContentLoaded', () => {
  const button = document.getElementById('counter');
  let count = 0;

  button.addEventListener('click', () => {
    count++;
    button.textContent = \`Count: \${count}\`;
  });
});
`,
  });

  return {
    name: ui.name,
    type: 'ui',
    files,
  };
}

function generateUIGitignore(): string {
  return `# Dependencies
node_modules/

# Build output
dist/
build/

# Logs
*.log

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
`;
}
