// Individual CDKTF resources for GCP
export { vpcNetwork } from './vpc-network.js';
export { vpcConnector } from './vpc-connector.js';
export { cloudFunction } from './cloud-function.js';
export { cloudRun } from './cloud-run.js';
export { artifactRegistry } from './artifact-registry.js';
export { loadBalancer } from './load-balancer.js';
export { storageBucket } from './storage-bucket.js';
export { storageWebsite } from './storage-website.js';
// GCP Kernel moved to @stacksolo/plugin-gcp-kernel
