/**
 * ConfigMap manifest generator
 * Creates environment variable ConfigMap for emulator hosts
 */

import type { K8sConfigMap, GeneratedManifest } from './types';
import { generateYamlDocument } from './yaml';
import { sanitizeNamespaceName } from './namespace';

export interface ConfigMapOptions {
  projectName: string;
  gcpProjectId?: string;
  firestoreEmulatorHost?: string;
  authEmulatorHost?: string;
  pubsubEmulatorHost?: string;
  additionalEnv?: Record<string, string>;
}

/**
 * Generate ConfigMap manifest with emulator hosts
 */
export function generateConfigMap(options: ConfigMapOptions): GeneratedManifest {
  const namespace = sanitizeNamespaceName(options.projectName);

  const data: Record<string, string> = {
    NODE_ENV: 'development',
    // StackSolo runtime environment variables
    STACKSOLO_PROJECT_NAME: options.projectName,
    GATEWAY_URL: 'http://gateway:8000',
    GCP_PROJECT_ID: options.gcpProjectId || `demo-${options.projectName}`,
  };

  // Add emulator hosts with in-cluster service names
  if (options.firestoreEmulatorHost !== undefined) {
    data.FIRESTORE_EMULATOR_HOST = options.firestoreEmulatorHost;
  } else {
    data.FIRESTORE_EMULATOR_HOST = 'firebase-emulator:8080';
  }

  if (options.authEmulatorHost !== undefined) {
    data.FIREBASE_AUTH_EMULATOR_HOST = options.authEmulatorHost;
  } else {
    data.FIREBASE_AUTH_EMULATOR_HOST = 'firebase-emulator:9099';
  }

  if (options.pubsubEmulatorHost !== undefined) {
    data.PUBSUB_EMULATOR_HOST = options.pubsubEmulatorHost;
  } else {
    data.PUBSUB_EMULATOR_HOST = 'pubsub-emulator:8085';
  }

  // Add any additional environment variables
  if (options.additionalEnv) {
    Object.assign(data, options.additionalEnv);
  }

  const configMap: K8sConfigMap = {
    apiVersion: 'v1',
    kind: 'ConfigMap',
    metadata: {
      name: 'stacksolo-env',
      namespace,
      labels: {
        'app.kubernetes.io/managed-by': 'stacksolo',
        'stacksolo.dev/project': options.projectName,
      },
    },
    data,
  };

  const content = generateYamlDocument(
    configMap as unknown as Record<string, unknown>,
    `StackSolo Environment ConfigMap\nGenerated by: stacksolo dev\n\nThis ConfigMap provides emulator hosts to all pods.`
  );

  return {
    filename: 'configmap.yaml',
    content,
  };
}
