/**
 * Namespace manifest generator
 * Creates isolated K8s namespace for the project
 */

import type { K8sNamespace, GeneratedManifest } from './types';
import { generateYamlDocument } from './yaml';

/**
 * Generate namespace manifest for a project
 */
export function generateNamespace(projectName: string): GeneratedManifest {
  const namespace: K8sNamespace = {
    apiVersion: 'v1',
    kind: 'Namespace',
    metadata: {
      name: sanitizeNamespaceName(projectName),
      labels: {
        'app.kubernetes.io/managed-by': 'stacksolo',
        'stacksolo.dev/project': projectName,
      },
    },
  };

  const content = generateYamlDocument(
    namespace as unknown as Record<string, unknown>,
    `StackSolo Namespace: ${projectName}\nGenerated by: stacksolo dev`
  );

  return {
    filename: 'namespace.yaml',
    content,
  };
}

/**
 * Sanitize project name for K8s namespace
 * - Must be lowercase
 * - Must start with a letter
 * - Can only contain letters, numbers, and hyphens
 * - Max 63 characters
 */
export function sanitizeNamespaceName(name: string): string {
  let sanitized = name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/--+/g, '-')
    .replace(/^-/, '')
    .replace(/-$/, '');

  // Ensure starts with a letter
  if (!/^[a-z]/.test(sanitized)) {
    sanitized = 'ns-' + sanitized;
  }

  // Truncate to 63 characters
  return sanitized.slice(0, 63);
}
